-- Create a DB called hbtn_0d_usa and a table cities
-- cities id must be a unique autogenerated id, can't be null and 
-- is a primary key.
-- cities must have a state_id which can't be null and is a foreign key to the states table
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.cities(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
	state_id INT NOT NULL,
	name VARCHAR(256) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (state_id) REFERENCES states(id)
	);
